In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10, size=(5,5))
arr

In [ ]:
# 전치
arr.T
np.transpose(arr)

In [ ]:
# 행렬곱, 내적
np.dot(arr.T, arr)

In [ ]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a, 0,1) # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')

y = a.T
y = np.transpose(a)
y = np.transpose(a)
print(y)

In [ ]:
# 1 ~ 100을 아래와 같이 출력하세요.

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)

In [ ]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


In [ ]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape,'\n')

In [ ]:
# (1,2,3) -> (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

In [ ]:
arr=arr.reshape(4,4)
print(arr,arr.shape)

In [ ]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요(shape 확인)

In [ ]:
arr=np.arange(16).reshape(16)
print(arr,arr.shape)

In [ ]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

In [ ]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype=float))

In [ ]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

In [ ]:
arr = np.random.randn(10)
# print(arr.mean(),'\n')
# print(arr.std())
arr

In [ ]:
# 양수인 원소의 개수
(arr > 0).sum()

In [ ]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False, True,True])
bools.any()

In [ ]:
# 모든 원소가 True인지 검사
bools.all()

In [ ]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)

In [ ]:
# arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr)

In [ ]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

In [ ]:
# np.sort()
np.random.seed(0)
arr = np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

In [ ]:
sorted = np.sort(arr)
print(sorted)

In [ ]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis=0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis=1)
print(sort_ar2d_axis1)

In [ ]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
# arr = np.random.randn(6)
print(arr,'\n')
arr.sort() # 원본 반영
print(arr)

In [ ]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬, default
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr)

In [ ]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

In [ ]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

In [ ]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

In [ ]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

In [ ]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

In [ ]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['a']

In [ ]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10,dtype=int)
a

In [ ]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

In [ ]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력

In [ ]:
a= np.arange(10)
a1 = a[a>5]
a1

In [ ]:
# Q. a에서 최대값, 최소값의 인덱스 출력

In [ ]:
a = np.arange(1,10)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

In [ ]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.

In [ ]:
np.argsort(a)[::-1]

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
b=np.ones((10,10))
b[1:9,1:9]=0
b

In [ ]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
b=np.zeros((10,10))
b[2:8,2:8]=1
b

In [ ]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile함수)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
n=np.zeros((8,8))
n[[1,3,5,7]]=[1,0]*4
n[[0,2,4,6]]=[0,1]*4
n

In [ ]:
n=np.zeros((8,8))
a=np.tile([0,1],4)
b=np.tile([1,0],4)
n[[1,3,5,7]]=a
n[[0,2,4,6]]=b

n

In [ ]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
a=np.arange(336).reshape(6,7,8)
a
np.where(a==99)

In [ ]:
a# [도전과제] np.arange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
a= np.arange(1,5)
arr=np.eye(5,k=-1,like=a)
c=0
for i in a:
    arr[i][c]=i
    c+=1
arr.astype('int32')

[파이썬 random 함수]

In [4]:
import random
import numpy as np
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3
                   ),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.9824183138166586 

6 

12.16128464204936 

7 

2 

[1, 5, 4] 

[5, 4, 3, 1, 2]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [5]:
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

5 

10 

[1 5 0 8 9 4 0 5 3 2] 

[12 16 18 10 10 10 12 10 14 16] 

[[12 17 16 13 14]
 [10 10 13 13 19]
 [15 17 14 19 10]]


In [ ]:
r = np.random.rand(6) # 0 ~ 1 사이의 균일분포
print(r,'\n')
r.mean()

[0.35939011 0.92422949 0.5613698  0.29359141 0.93212749 0.62799602] 



0.6164507206061188

In [ ]:
# 표준 정규분포
r = np.random.randn(10000)
print(r,'\n')
r.mean()

[-0.10321885  0.4105985   0.14404357 ... -1.08502512  0.97226233
  1.43147168] 



-0.01893802539118709

In [7]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([3, 4, 1, 5, 2])

In [8]:
np.random.choice(list)

5

In [11]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [ ]:
np.random.uniform(1.0,2.0, 10) # 1-2 사이의 10개 '실수'를 리턴

array([1.23196751, 1.41547268, 1.85182497, 1.73567716, 1.33340048,
       1.12387434, 1.49182714, 1.22099167, 1.25233108, 1.42272584])

In [12]:
print(np.random.uniform(0,1,(2,3))) # 0-1 사이의 2행3열 '실수'를 리턴

[[0.90068438 0.62944673 0.11897971]
 [0.90468783 0.92323912 0.57101956]]


In [ ]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.40762345, 0.86121214, 0.95243613],
       [0.57615261, 0.98855528, 0.58242609]])

In [ ]:
!pip install pandas

In [16]:
ar = np.random.rand(4,8)
ar

array([[0.17537096, 0.20784331, 0.49352924, 0.54306758, 0.31726844,
        0.56908743, 0.71891429, 0.00279072],
       [0.27225846, 0.88486687, 0.63505512, 0.30274555, 0.68196532,
        0.3812213 , 0.03023649, 0.2433459 ],
       [0.22884372, 0.25595418, 0.74148129, 0.90315151, 0.99117438,
        0.92811475, 0.58563334, 0.93826151],
       [0.73146375, 0.835947  , 0.59504218, 0.62951737, 0.77661103,
        0.19632042, 0.75074755, 0.18264062]])

In [ ]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.729431  0.684862  0.868469  0.522983  0.030574  0.146772  0.520409   
1  0.544840  0.048985  0.991160  0.719574  0.350430  0.803454  0.833256   
2  0.352445  0.806314  0.018128  0.649153  0.013020  0.929774  0.325772   
3  0.376991  0.381680  0.877992  0.835450  0.742619  0.508451  0.677759   

          7  
0  0.461370  
1  0.383248  
2  0.476830  
3  0.322290   <class 'pandas.core.frame.DataFrame'>


In [ ]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.729431  0.684862  0.868469  0.522983  0.030574  0.146772  0.520409   
1  0.544840  0.048985  0.991160  0.719574  0.350430  0.803454  0.833256   
2  0.352445  0.806314  0.018128  0.649153  0.013020  0.929774  0.325772   
3  0.376991  0.381680  0.877992  0.835450  0.742619  0.508451  0.677759   

       time  
0  0.461370  
1  0.383248  
2  0.476830  
3  0.322290

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요.

In [56]:
import pandas as pd
id=np.random.randint(1000,2000,4)
gen=np.random.choice(['M','F'],4)
age=np.random.randint(20,40,4)

data=np.array([id,gen,age]).transpose()
df=pd.DataFrame(data,range(1,5),['id','sex','age'])

df


id sex age
1  1858   F  35
2  1157   F  22
3  1746   F  30
4  1701   F  26

In [57]:
h = np.zeros((3, 10))
id_ = np.random.randint(1, 1000, size = (1, 10))
gender = np.random.randint(2, size = (1, 10))
age = np.random.randint(0, 120, size = (1, 10))

h[0] = id_
h[1] = gender
h[2] = age

h = np.transpose(h)
print(h,'\n')

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df

[[113.   0.  46.]
 [608.   0. 100.]
 [623.   0. 115.]
 [521.   0.  75.]
 [690.   0.  29.]
 [604.   0.  38.]
 [692.   1.  57.]
 [222.   1.  34.]
 [110.   0. 117.]
 [ 80.   0.  44.]] 



id  gender    age
1   113.0     0.0   46.0
2   608.0     0.0  100.0
3   623.0     0.0  115.0
4   521.0     0.0   75.0
5   690.0     0.0   29.0
6   604.0     0.0   38.0
7   692.0     1.0   57.0
8   222.0     1.0   34.0
9   110.0     0.0  117.0
10   80.0     0.0   44.0

In [ ]:
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
# df.id = np.array([1,2,3,4])
df.id = np.arange(1,5)
# df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2,size=4)
# df.age = np.array([20,30,40,50])
df.age = np.arange(1,5) * 10
df

id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [24]:
import numpy as np
import pandas as pd
columns=['id', 'gender', 'age','region','product_19','product_20','price_19','price_20',
                                   'quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
arr=np.zeros((1000,len(columns)))

df = pd.DataFrame(arr,range(1,1001),columns)

df.id = np.random.randint(1, 1001, size = 1000)
df.gender = np.random.randint(0, 2, size = 1000)
df.age = np.random.randint(0, 81, size = 1000)
df.region = np.random.randint(1, 11, size = 1000)
df.product_19 = np.random.randint(11111, 100000, size = 1000)
df.product_20 = np.random.randint(11111, 100000, size = 1000)
df.price_19 = np.random.uniform(1000.0,50000.0,1000)
df.price_20 = np.random.uniform(1000.0,50000.0,1000)
df.quantity_19 = np.random.randint(1,101, size = 1000)
df.quantity_20 = np.random.randint(1,101, size = 1000)
df.time_19 = np.random.randint(1,25, size = 1000)
df.time_20 = np.random.randint(1,25, size = 1000)
df.amount_19 = (df.price_19 * df.quantity_19)//1000
df.amount_20 = (df.price_20 * df.quantity_20)//1000
df.sales = np.where( df.amount_19 < df.amount_20,1,0)
df

id  gender  age  region  product_19  product_20      price_19  \
1     623       0   39       1       89464       40218  37647.970070   
2     628       0   38       2       14912       13346  38252.918243   
3     802       1   73       6       82965       80384  16772.960603   
4     818       0   56       1       86103       58661  14102.533431   
5     983       1   15       8       19247       47773  43278.013211   
...   ...     ...  ...     ...         ...         ...           ...   
996   615       1   26       6       47111       27558  30253.776581   
997   616       0   32      10       72734       21466  20574.505909   
998   872       1   23       8       72775       58187   8032.425624   
999   384       1   46       1       80492       40286  45684.417042   
1000   57       1   69       1       14737       41037  30443.215076   

          price_20  quantity_19  quantity_20  time_19  time_20  amount_19  \
1     32012.987382           54           55       10        8     2032.0   
2     15394.897209           82           69       10        6     3136.0   
3     43240.035223           11           91        4       18      184.0   
4     10539.499719           39           98        4        2      549.0   
5     16796.135355            5           60        3        6      216.0   
...            ...          ...          ...      ...      ...        ...   
996   12136.434817           12            4       20        5      363.0   
997    4545.720468           47           42       23       13      967.0   
998    3619.184715           25           98        1        2      200.0   
999   33793.125364            4           26       11       21      182.0   
1000  16203.194552            3           22        5       24       91.0   

      amount_20  sales  
1        1760.0      0  
2        1062.0      0  
3        3934.0      1  
4        1032.0      1  
5        1007.0      1  
...         ...    ...  
996        48.0      0  
997       190.0      0  
998       354.0      1  
999       878.0      1  
1000      356.0      1  

[1000 rows x 15 columns]