In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10, size=(5,5))
arr

In [ ]:
# 전치
arr.T
np.transpose(arr)

In [ ]:
# 행렬곱, 내적
np.dot(arr.T, arr)

In [ ]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a, 0,1) # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')

y = a.T
y = np.transpose(a)
y = np.transpose(a)
print(y)

In [ ]:
# 1 ~ 100을 아래와 같이 출력하세요.

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)

In [ ]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


In [ ]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape,'\n')

In [ ]:
# (1,2,3) -> (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
import numpy as np
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

In [ ]:
arr=arr.reshape(4,4)
print(arr,arr.shape)

In [ ]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요(shape 확인)

In [ ]:
arr=np.arange(16).reshape(16)
print(arr,arr.shape)

In [ ]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

In [ ]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype=float))

In [ ]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

In [ ]:
arr = np.random.randn(10)
# print(arr.mean(),'\n')
# print(arr.std())
arr

In [ ]:
# 양수인 원소의 개수
(arr > 0).sum()

In [ ]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False, True,True])
bools.any()

In [ ]:
# 모든 원소가 True인지 검사
bools.all()

In [ ]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)

In [ ]:
# arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr)

In [ ]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

In [ ]:
# np.sort()
np.random.seed(0)
arr = np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

In [ ]:
sorted = np.sort(arr)
print(sorted)

In [ ]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d, axis=0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d, axis=1)
print(sort_ar2d_axis1)

In [ ]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
# arr = np.random.randn(6)
print(arr,'\n')
arr.sort() # 원본 반영
print(arr)

In [ ]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬, default
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr)

In [ ]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0)
print(arr)

In [ ]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

In [ ]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

In [ ]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

In [ ]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

In [ ]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [ ]:
arch = np.load('array_archive.npz')
arch['a']

In [ ]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10,dtype=int)
a

In [ ]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

In [ ]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력

In [ ]:
a= np.arange(10)
a1 = a[a>5]
a1

In [ ]:
# Q. a에서 최대값, 최소값의 인덱스 출력

In [ ]:
a = np.arange(1,10)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

In [ ]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.

In [ ]:
np.argsort(a)[::-1]

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
b=np.ones((10,10))
b[1:9,1:9]=0
b

In [ ]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
b=np.zeros((10,10))
b[2:8,2:8]=1
b

In [ ]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile함수)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
n=np.zeros((8,8))
n[[1,3,5,7]]=[1,0]*4
n[[0,2,4,6]]=[0,1]*4
n

In [ ]:
n=np.zeros((8,8))
a=np.tile([0,1],4)
b=np.tile([1,0],4)
n[[1,3,5,7]]=a
n[[0,2,4,6]]=b

n

In [ ]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
a=np.arange(336).reshape(6,7,8)
a
np.where(a==99)

In [ ]:
a# [도전과제] np.arange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
a= np.arange(1,5)
arr=np.eye(5,k=-1,like=a)
c=0
for i in a:
    arr[i][c]=i
    c+=1
arr.astype('int32')