Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
z = np.arange(10)
print(z,type(z))

In [ ]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_array2 = my_arr * 2

In [ ]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

In [ ]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분표에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스
print(data,'\n')
print(data * 10, '\n')
print(data + data)

In [ ]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px;'>

In [ ]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

In [ ]:
print(arr2.ndim,'\n')
print(arr2.shape)

In [ ]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) # (,옇)이 아닌 (열,) 형태로 출력

In [ ]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[2,3,4]])
print(array2,type(array2),array2.shape)

In [ ]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array21 = np.array([[1,2,3]])
print(array21,array21.shape)

In [ ]:
# 3차원
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]],dtype=object)
print(array3,array3.shape,'\n')
print(type(array3))

In [ ]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy 는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [ ]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

In [ ]:
print(np.ones((2,3,2)))

In [ ]:
ar1 = np.full((2,2),5)
ar1

In [ ]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
ar2

In [ ]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [ ]:
# arange 함수 : python의 range함수의 배열 버전
arr1 = np.arange(15)
arr1

In [ ]:
arr2 = arr1.reshape(3,5)
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3,arr3.shape)

In [ ]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

In [ ]:
# 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력하세요

In [ ]:
array1 = np.arange(30)
array2 = array1.reshape(5,6)
print(array2,array2.shape,'\n')
array3 = array2.reshape(2,3,5)
print(array3,array3.shape)

In [ ]:
# reshape(-1,-1) 이용, 차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

In [ ]:
# 2 -> 1, 3차원으로 변환하여 출력
ar12

In [ ]:
ar1=ar12.reshape(-1,)
ar3=ar12.reshape(-1,2,5)
print(ar1,ar1.shape,'\n')
print(ar3,ar3.shape,'\n')

In [ ]:
# 3 -> 1,2차원으로 변환하여 출력
ar3

In [ ]:
ar3 = np.arange(30).reshape(3,2,5)
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(3,-1)

print(ar31,'\n')
print(ar32)

행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [ ]:
# 정방행렬
a = np.full((5,5), 7)
a

In [ ]:
# 항등행렬, 단위행렬
a = np.eye(5)
a

In [ ]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

ndarray 데이터 형태 지정 및 변경
<img src='데이터형태.jpg' STYLE='width:300px;'>

In [ ]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2, arr2.dtype)

In [ ]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

In [ ]:
np.ones(10)

In [ ]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf. zeros 함수
# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,), dtype=np.int8))
print(np.zeros(shape=(10,), dtype=np.int8))

In [ ]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype='S')
arr = np.array([1,2,3,4], dtype=np.string_)
print(arr, arr.dtype)

In [ ]:
arr1 = arr.astype('float32')
print(arr1,arr1.dtype)

In [ ]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)
print(array_e2,array_e2.dtype)

In [ ]:
# 배열의 산술 연산
# arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

In [ ]:
arr2 > arr

In [ ]:
# 기본 사칙연산

value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)
print(value1+value2,'\n')
print(np.add(value1,value2),'\n')

print(value2-value1,'\n')
print(np.subtract(value2,value1),'\n')

print(value1*value2,'\n')
print(np.multiply(value1,value2),'\n')

print(value2/value1,'\n')
print(np.divide(value2,value1))


In [ ]:
arr = np.random.randn(2,2)
arr

In [ ]:
arr.mean().round(4)

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.mean(axis=0)b

In [ ]:
arr.sum().round(4)

In [ ]:
arr.cumprod()

In [ ]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

In [ ]:
arr2d[2:]

In [ ]:
arr2d[2][2]

In [ ]:
arr2d[:,0]

In [ ]:
arr2d[:2,:]

In [ ]:
# arr2d를 다은 방식으로 아래와 같이 출력하세요.
[[1, 2, 3],
[4, 5, 6]]

In [ ]:
# arr2d[:2][:]
arr2d[[0,2],:]

In [ ]:
# arr2d에서 [3,6], [[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
print()
print(arr2d[:2,:2])

In [ ]:
arr = np.arange(30).reshape(5,6)
arr

In [ ]:
[14,15,16]
[3,9]
[1,7,13]

In [ ]:
arr[2][2:5]

In [ ]:
arr[[0,1],3]
arr[:2,3]

In [ ]:
arr[:3,1]
arr[[0,1,2],1]

In [ ]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li, type(li))

In [ ]:
# Boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

In [ ]:
# arr1d에서 일반 인덱스를 이용해서 [6 7 8 9]를 출력하세요.
print(arr1d[5:])

In [ ]:
# Q. 1 ~ 14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱싱으로 출력하세요.

array_e = np.arange(1,15)
array = array_e[(array_e/2) > 5]
print(array)

In [ ]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]

In [ ]:
# != 부정
data[names != 'Bob']

In [ ]:
# Bob이거나 Will인 것 출력
mask = (names == 'Bob') | (names == 'Will')
data[mask]

In [ ]:
# 음수를 모두 0으로 처리하여 출력
data[data<0] = 0
print(data)

In [ ]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
[i for i in range(1,101) if i%3==0 ]
     

In [ ]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

In [ ]:
[i for i in range(1,101) if i%10==0 ]

In [ ]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.

In [ ]:
data = np.random.randn(5,5)
data.mean()

In [ ]:
data.std()

In [ ]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
!pip install numpy

In [ ]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
import numpy as np
np.info(np.add)

In [ ]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [39]:
n=np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a[::-1]

In [36]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.

a = np.array([1,2,0,0,4,0])
a[a!=0]

array([1, 2, 4])