In [1]:
!pip install numpy

In [11]:
import numpy as np
z=np.arange(10)
print(z,type(z))


[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [12]:
arr=np.arange(1000000)
lst=list(range(1000000))


Wall time: 0 ns


In [18]:
%time for _ in range(10):a=arr*2

Wall time: 13 ms


In [19]:
%time for _ in range(10):a=[x*2 for x in lst]

Wall time: 591 ms


In [28]:
data=np.random.randn(2,3)
print(data,'\n')
print(data * 10, '\n')
print(data+data)

[[ 0.98018488  0.36968664  1.73662018]
 [-0.35286022 -0.03145249  2.62343409]] 

[[ 9.80184884  3.69686637 17.36620179]
 [-3.52860218 -0.3145249  26.23434091]] 

[[ 1.96036977  0.73937327  3.47324036]
 [-0.70572044 -0.06290498  5.24686818]]


In [31]:
print(data.shape)
print(data.dtype)
print(data.ndim) #차원수

(2, 3)
float64
2


<img src='numpy차원.jpg' style='width:300px'>

In [32]:
data2=[[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2=np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [35]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [37]:
arr1=np.array([1,2,3])
print(arr1,type(arr1))
print(arr1.ndim)
print(arr1.shape)#(행,열)이 아닌 (열,행)으로 출력

[1 2 3] <class 'numpy.ndarray'>
1
(3,)


In [41]:
arr1=np.array([[1,2,5],[6,8,9]])
print(arr1,type(arr1))
print(arr1.ndim)
print(arr1.shape)#(행,열)이 아닌 (열,행)으로 출력

[[1 2 5]
 [6 8 9]] <class 'numpy.ndarray'>
2
(2, 3)


In [42]:
arr1=np.array([[1,5,8]])
print(arr1,type(arr1))
print(arr1.ndim)
print(arr1.shape)

[[1 5 8]] <class 'numpy.ndarray'>
2
(1, 3)


In [47]:
arr1=np.array([[[1,5,8],[2,3,7]],[[6,2,1],[8,9,3]]])
print(arr1,type(arr1))
print(arr1.ndim)
print(arr1.shape)

[[[1 5 8]
  [2 3 7]]

 [[6 2 1]
  [8 9 3]]] <class 'numpy.ndarray'>
3
(2, 2, 3)


In [ ]:
#경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

In [52]:
print(np.zeros(10))
print(np.zeros((2,3,2)))



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [54]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
arr=np.eye(3) #대각만 1인 배열 항등행렬,단위행렬
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
arr=np.full((2,3),5)
arr

array([[5, 5, 5],
       [5, 5, 5]])

In [71]:
arr1=np.arange(15)
arr2= arr1.reshape(3,5)
print(arr2)
print()
arr3= arr1.reshape(1,3,5)
print(arr3)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


In [75]:
arr1=np.arange(10)
arr2= arr1.reshape(5,2)
print(arr2,arr2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [78]:
arr1=np.arange(30)
arr2= arr1.reshape(6,5)
arr3= arr1.reshape(5,3,2)

print(arr2)
print()
print(arr3)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


In [84]:
arr1=np.arange(30) #-1을 넣으면 나머지 수가 알아서 계산댐
arr2= arr1.reshape(3,-1)
print(arr2)

print(arr1.reshape(2,3,-1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [92]:
arr3=arr2.reshape(2,3,-1)
print(arr3)
print(arr2.reshape(-1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [98]:
arr3.reshape(-1)
arr3.reshape((2,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
#정방행렬

<img src='데이터형태.jpg' style='width:300px'>

In [99]:
arr=np.array([1,2,3,4], dtype='S')
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [101]:
arr1=arr.astype(float)
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float64
