In [ ]:
#1차원데이터

In [33]:
import numpy as np
import pandas as pd

df=pd.read_csv('data/ch2_scores_em.csv')
df.head()

student number  english  mathematics
0               1       42           65
1               2       69           80
2               3       56           63
3               4       41           63
4               5       57           76

In [7]:
scores= np.array(df.english)[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [37]:
score_df=pd.DataFrame({'score':scores}, index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name='student'))

score_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [38]:
print(sum(scores),len(scores))
print(np.mean(scores))

score_df.mean()

550 10
55.0


score    55.0
dtype: float64

In [39]:
sorted_scores=np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [40]:
#중앙값
n=len(sorted_scores)
if n %2==0:
    m0=sorted_scores[n//2-1]
    m1=sorted_scores[n//2]
    median=(m0+m1)/2
else:
    median=sorted_Score[(n+1)//2-1]
median

56.5

In [41]:
print(np.median(scores))
score_df.median()

56.5


score    56.5
dtype: float64

In [50]:
#최빈값
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [44]:
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [49]:
#편차
mean=np.mean(scores)
print(mean)
deviation=scores-mean
deviation

55.0


array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [51]:
np.mean(deviation)

0.0

In [61]:
arr=np.random.randint(1,20,size=20)
arr

array([ 2,  7, 10, 11,  1,  8,  5, 12, 18,  4, 15,  3, 15, 13,  8,  2, 17,
        2, 14,  1])

In [62]:
arr.mean()

8.4

In [65]:
dev=arr-arr.mean()
dev

array([-6.4, -1.4,  1.6,  2.6, -7.4, -0.4, -3.4,  3.6,  9.6, -4.4,  6.6,
       -5.4,  6.6,  4.6, -0.4, -6.4,  8.6, -6.4,  5.6, -7.4])

In [68]:
np.sum(dev)

-7.105427357601002e-15

분산
- numpy 와 pandas 는 서로 다른 분산을 기본으로 설정하여 계산
    * numpy는 표본분산, pandas는 불편분산
    * pandas에서 표본분산을 계산하려면 var 메소드의 인수를 ddof=0이라고 설정,불편분산은 ddfo=1 일때 해당

In [78]:
(deviation**2).mean()

86.0

In [76]:
np.mean(deviation**2)

86.0

In [72]:
np.var(scores)

86.0

In [75]:
score_df.var()

score    95.555556
dtype: float64

In [85]:
df=score_df.copy()
df['deviation']=deviation
df['square']=np.square(deviation)

df.mean()

score        55.0
deviation     0.0
square       86.0
dtype: float64

In [91]:
#표준편차
np.sqrt(np.var(scores,ddof=0))

9.273618495495704

In [94]:
np.std(scores,ddof=0)

9.273618495495704

In [96]:
df.std(ddof=0)

score         9.273618
deviation     9.273618
square       74.315543
dtype: float64

In [98]:
#범위와 4분위수 범위
np.max(scores)-np.min(scores)

28

In [102]:
scores_q1=np.percentile(scores,25)
scores_q3=np.percentile(scores,75)
iqr=scores_q3-scores_q1
iqr

15.0

In [103]:
pd.Series(scores).describe()

count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64

In [104]:
#데이터 정규화
print(f'평균: {scores.mean()}, 표준편차: {scores.std().round(4)}')

평균: 55.0, 표준편차: 9.2736


In [105]:
#표준화
z=(scores-np.mean(scores))/np.std(scores)
z

array([-1.40182605,  1.50965882,  0.10783277, -1.50965882,  0.21566555,
       -0.75482941,  1.07832773, -0.64699664,  1.07832773,  0.32349832])

In [107]:
np.mean(z),np.std(z)

(-1.6653345369377347e-17, 0.9999999999999999)

In [108]:
z=50+10*(scores-np.mean(scores))/np.std(scores)
z

array([35.98173948, 65.09658825, 51.07832773, 34.90341175, 52.15665546,
       42.45170588, 60.78327732, 43.53003361, 60.78327732, 53.2349832 ])

In [110]:
score_df['deviation_value']=z
score_df

score  deviation_value
student                        
A           42        35.981739
B           69        65.096588
C           56        51.078328
D           41        34.903412
E           57        52.156655
F           48        42.451706
G           65        60.783277
H           49        43.530034
I           65        60.783277
J           58        53.234983

In [114]:
df = pd.read_csv('./data/ch2_scores_em.csv')
eng_s=np.array(df.english)
pd.Series(eng_s).describe()

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [118]:
freq, _=np.histogram(eng_s,bins=10,range=(0,100))
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64)

In [122]:
freq_class=[f'{i}~{i+10}' for i in range(0,100,10)]
freq_dist_df=pd.DataFrame({'frequency' : freq},
                          index=pd.Index(freq_class,name='class'))

freq_dist_df


frequency
class            
0~10            0
10~20           0
20~30           0
30~40           2
40~50           8
50~60          16
60~70          18
70~80           6
80~90           0
90~100          0

In [124]:
# 계급값 : 각 계급을 대표하는 값으로 계급의 중앙값이 이용됨
class_value = [(i+(i+10))//2 for i in range(0,100,10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [126]:
#상대도수 : 해당 계급 데이터의 상대적인 비율
rel_freq = freq / freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [127]:
#누적상대도수 : 해당 계급까지의 상대도수 합
cum_rel_freq = np.cumsum(rel_freq) # 누적합
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [131]:
freq_dist_df['class value']=class_value
freq_dist_df['relative frequency']=rel_freq
freq_dist_df['cumulative relative frequency']=cum_rel_freq
freq_dist_df

frequency  class value  relative frequency  \
class                                                
0~10            0            5                0.00   
10~20           0           15                0.00   
20~30           0           25                0.00   
30~40           2           35                0.04   
40~50           8           45                0.16   
50~60          16           55                0.32   
60~70          18           65                0.36   
70~80           6           75                0.12   
80~90           0           85                0.00   
90~100          0           95                0.00   

        cumulative relative frequency  
class                                  
0~10                             0.00  
10~20                            0.00  
20~30                            0.00  
30~40                            0.04  
40~50                            0.20  
50~60                            0.52  
60~70                            0.88  
70~80                            1.00  
80~90                            1.00  
90~100                           1.00

In [142]:
#최빈값
freq_dist_df.loc[freq_dist_df['frequency'].idxmax(),'class value']

65