Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [ ]:
!pip install numpy

In [1]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [4]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 13 ms


In [7]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 582 ms


In [8]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분표에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스
print(data,'\n')
print(data * 10, '\n')
print(data + data)

[[ 0.49530622 -0.27194412 -2.27409961]
 [-0.06689666  0.47497492 -0.94044956]] 

[[  4.95306217  -2.71944124 -22.74099614]
 [ -0.66896663   4.7497492   -9.40449557]] 

[[ 0.99061243 -0.54388825 -4.54819923]
 [-0.13379333  0.94994984 -1.88089911]]


In [9]:
print(data.shape) # 크기
print(data.dtype) # 데이터 타입
print(data.ndim) # 차원

(2, 3)
float64
2


다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px;'>

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [11]:
print(arr2.ndim,'\n') #dimension 의 수
print(arr2.shape)

2 

(2, 4)


In [13]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) # (,옇)이 아닌 (열,) 형태로 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [14]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터
array2 = np.array([[1,2,3],[2,3,4]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)


In [15]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array21 = np.array([[1,2,3]])
print(array21,array21.shape)

[[1 2 3]] (1, 3)


In [16]:
# 3차원
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]],dtype=object)
print(array3,array3.shape,'\n')
print(type(array3))

[[[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]

 [[1 2 3 4 5]
  [6 7 8 9 10]]] (3, 2, 5) 

<class 'numpy.ndarray'>


In [ ]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy 는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [17]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [18]:
print(np.ones((2,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [19]:
ar1 = np.full((2,2),5)
ar1

array([[5, 5],
       [5, 5]])

In [20]:
# 항등행렬, 단위행렬
ar2 = np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [22]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,'\n')

array_zeros = np.zeros_like(array)
print(array_zeros,'\n')

array_ones = np.ones_like(array)
print(array_ones,'\n')

array_full = np.full_like(array,5)
print(array_full)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [24]:
# arange 함수 : python의 range함수의 배열 버전
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr2 = arr1.reshape(3,5)
print(arr2,arr2.shape,'\n')
arr3 = arr1.reshape(1,3,5)
print(arr3,arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [26]:
# Q. array1을 생성하고 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
# 0~29 일차원 배열을 생성한 후 다시 2,3차원 배열로 변환하여 출력하세요

In [28]:
array1 = np.arange(30)
array2 = array1.reshape(5,6)
print(array2,array2.shape,'\n')
array3 = array2.reshape(2,3,5)
print(array3,array3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (2, 3, 5)


In [29]:
# reshape(-1,-1) 이용, 차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(3,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [30]:
# 2 -> 1, 3차원으로 변환하여 출력
ar12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [31]:
ar1=ar12.reshape(-1,)
ar3=ar12.reshape(-1,2,5)
print(ar1,ar1.shape,'\n')
print(ar3,ar3.shape,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [32]:
# 3 -> 1,2차원으로 변환하여 출력
ar3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [33]:
ar3 = np.arange(30).reshape(3,2,5)
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(3,-1)

print(ar31,'\n')
print(ar32)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [34]:
# 정방행렬
a = np.full((5,5), 7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [35]:
# 항등행렬, 단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ndarray 데이터 형태 지정 및 변경
<img src='데이터형태.jpg' STYLE='width:300px;'>

In [37]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2, arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [38]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf. zeros 함수
# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.
print(np.empty(shape=(10,), dtype=np.int8))
print(np.zeros(shape=(10,), dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [41]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype='S')
arr = np.array([1,2,3,4], dtype=np.string_)
print(arr, arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [42]:
arr1 = arr.astype('float32')
print(arr1,arr1.dtype)

[1. 2. 3. 4.] float32


In [43]:
# 정수와 실수로 구성된 list_e = [1.2,2.3,3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)
print(array_e2,array_e2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [44]:
# 배열의 산술 연산
# arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [45]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [46]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [49]:
# 기본 사칙연산

value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)
print(value1+value2,'\n')
print(np.add(value1,value2),'\n')

print(value2-value1,'\n')
print(np.subtract(value2,value1),'\n')

print(value1*value2,'\n')
print(np.multiply(value1,value2),'\n')

print(value2/value1,'\n')
print(np.divide(value2,value1))


[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [54]:
arr = np.random.randn(2,2)
arr

array([[1.0599356 , 0.68478367],
       [0.44128536, 0.18964492]])

In [55]:
arr.mean().round(4)

0.5939

In [56]:
arr.mean(axis=1)

array([0.87235963, 0.31546514])

In [57]:
arr.mean(axis=0)

array([0.75061048, 0.4372143 ])

In [58]:
arr.sum().round(4)

2.3756

In [59]:
arr.cumprod() #누적곱

array([1.0599356 , 0.72582659, 0.32029664, 0.06074263])

In [61]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2d[2:]

array([[7, 8, 9]])

In [63]:
arr2d[2][2]

9

In [64]:
arr2d[:,0]

array([1, 4, 7])

In [65]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# arr2d를 다은 방식으로 아래와 같이 출력하세요.
[[1, 2, 3],
[4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [67]:
# arr2d[:2][:]
arr2d[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [68]:
# arr2d에서 [3,6], [[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
print()
print(arr2d[:2,:2])

[3 6]

[[1 2]
 [4 5]]


In [69]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
[14,15,16]
[3,9]
[1,7,13]

[1, 7, 13]

In [71]:
arr[2][2:5]

array([14, 15, 16])

In [72]:
arr[[0,1],3]
arr[:2,3]

array([3, 9])

In [73]:
arr[:3,1]
arr[[0,1,2],1]

array([ 1,  7, 13])

In [74]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li, type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [75]:
# Boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d > 5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [76]:
# arr1d에서 일반 인덱스를 이용해서 [6 7 8 9]를 출력하세요.
print(arr1d[5:])

[6 7 8 9]


In [77]:
# Q. 1 ~ 14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱싱으로 출력하세요.

array_e = np.arange(1,15)
array = array_e[(array_e/2) > 5]
print(array)

[11 12 13 14]


In [78]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[ 1.20284127  0.849647    0.33617642  2.58397747]
 [ 0.09602838  0.08048296  0.75770227  2.2230844 ]
 [-0.20346613  0.80521279  0.67809886 -0.46164842]
 [-0.24511396 -1.04155798 -1.23493055  0.29146957]
 [-0.18345428 -1.82839576  0.2466142   0.57748442]
 [-1.01987907  1.62734198 -1.38040469 -2.76446371]
 [ 0.52526362  1.64472619  1.62793492  0.53314547]]


In [79]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [80]:
data[names == 'Bob']

array([[ 1.20284127,  0.849647  ,  0.33617642,  2.58397747],
       [-0.24511396, -1.04155798, -1.23493055,  0.29146957]])

In [81]:
data[names == 'Bob', 2:]

array([[ 0.33617642,  2.58397747],
       [-1.23493055,  0.29146957]])

In [82]:
# != 부정
data[names != 'Bob']

array([[ 0.09602838,  0.08048296,  0.75770227,  2.2230844 ],
       [-0.20346613,  0.80521279,  0.67809886, -0.46164842],
       [-0.18345428, -1.82839576,  0.2466142 ,  0.57748442],
       [-1.01987907,  1.62734198, -1.38040469, -2.76446371],
       [ 0.52526362,  1.64472619,  1.62793492,  0.53314547]])

In [83]:
# Bob이거나 Will인 것 출력
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 1.20284127,  0.849647  ,  0.33617642,  2.58397747],
       [-0.20346613,  0.80521279,  0.67809886, -0.46164842],
       [-0.24511396, -1.04155798, -1.23493055,  0.29146957],
       [-0.18345428, -1.82839576,  0.2466142 ,  0.57748442]])

In [84]:
# 음수를 모두 0으로 처리하여 출력
data[data<0] = 0
print(data)

[[1.20284127 0.849647   0.33617642 2.58397747]
 [0.09602838 0.08048296 0.75770227 2.2230844 ]
 [0.         0.80521279 0.67809886 0.        ]
 [0.         0.         0.         0.29146957]
 [0.         0.         0.2466142  0.57748442]
 [0.         1.62734198 0.         0.        ]
 [0.52526362 1.64472619 1.62793492 0.53314547]]


In [85]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
[i for i in range(1,101) if i%3==0 ]
     

[3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99]

In [86]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

In [87]:
[i for i in range(1,101) if i%10==0 ]

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [88]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.

In [89]:
data = np.random.randn(5,5)
data.mean()

0.2532262340510603

In [90]:
data.std()

0.9360449681055455

In [91]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
!pip check numpy

spyder 5.1.5 requires pyqt5, which is not installed.
spyder 5.1.5 requires pyqtwebengine, which is not installed.
daal4py 2021.3.0 requires daal, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
anaconda-project 0.10.1 requires ruamel-yaml, which is not installed.


In [92]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [95]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
#array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [96]:
n=np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [100]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [::-1]


[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [98]:
a=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [102]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.

a = np.array([1,2,0,0,4,0])
# a[a!=0]
np.nonzero(a) #인덱스를 반환

(array([0, 1, 4], dtype=int64),)

In [103]:
arr = np.empty((8,4))
arr

for i in range(8):
    arr[i]=i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [104]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [105]:
arr[[-3,-5,-1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [106]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [108]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [109]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [110]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])