In [4]:
import numpy as np

array1=np.array([1,2,3])
array2=np.array([[1,2,3],[2,3,4]])
array3=np.array([[[1,2,3]]])
print(array1,type(array1),array1.shape)
print(array2,type(array2),array2.shape)
print(array3,type(array3),array3.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)
[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)
[[[1 2 3]]] <class 'numpy.ndarray'> (1, 1, 3)


In [7]:
array_int=np.array([1,2,3])
print(array_int.dtype)

array_float = array_int.astype('float64')
print(array_float.dtype)

array_int2=array_float.astype('int32')
print(array_int2.dtype)

int32
float64
int32


In [10]:
za=np.zeros((3,2),dtype='int32')
print(za)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
one_array = np.ones((3,2))
print(one_array,one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [13]:
#reshape : 1 -> 2,3차원
ar1=np.arange(10)
print(ar1,ar1.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [16]:
print(ar1,'\n')
print(ar1.reshape(2,5),'\n')
print(ar1.reshape(1,2,5))


[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [22]:
#reshape -1 사용
ar1=np.arange(10)
print(ar1.reshape(2,-1))
print(ar1.reshape(5,2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]


In [24]:
#3차원 -> 2,1차원
ar3=np.arange(8).reshape((2,2,2))
ar3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
print(ar3.reshape(4,2))
print(ar3.reshape(-1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]


In [35]:
ar1=np.arange(1,10)
print(ar1)
value=ar1[1]
print(value)
print(ar1[-1])
print(ar1[-3])

[1 2 3 4 5 6 7 8 9]
2
9
7


In [42]:
ar2d=np.arange(1,10).reshape(3,3)
print(ar2d)
print(ar2d[0,0])
print(ar2d[0,1])
print(ar2d[1,0])
print(ar2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
8


In [43]:
#slicing
ar1=np.arange(1,20)
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
#456 161718
print(ar1[3:6])
print(ar1[-4:-1])

[4 5 6]
[16 17 18]


In [52]:
ar2d=np.arange(1,10).reshape(3,3)
print(ar2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
print(ar2d[1:,:])

[[4 5 6]
 [7 8 9]]


In [60]:
print(ar2d[:2,1:])

[[2 3]
 [5 6]]


In [72]:
print(ar2d[:2,:1].reshape(-1))
print(ar2d[:2,0])

[1 4]
[1 4]


In [79]:
#fancy indexing
ar1=np.arange(1,10).reshape(3,3)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
print(ar1[[0,1],2])


[3 6]


In [84]:
print(ar1[[0,1],:2])

[[1 2]
 [4 5]]


In [88]:
print(ar1[[0,1]])

[[1 2 3]
 [4 5 6]]


In [73]:
#boolean indexing
ar1=np.arange(1,10)
print(ar1)

[1 2 3 4 5 6 7 8 9]


In [75]:
print(ar1[5:])

[6 7 8 9]


In [92]:
ar=np.array([3,1,9,5])

#np : return지정해야댐
print(ar)
sort = np.sort(ar)
print(ar)

#내부 : 원본자동리턴
print(sort)
print(ar.sort())
print(ar)

[3 1 9 5]
[3 1 9 5]
[1 3 5 9]
None
[1 3 5 9]


In [95]:
#내림차순
sort_desc=np.sort(ar)[::-1]
print(sort_desc)

[9 5 3 1]


In [100]:
ar2=np.array([[8,12],[7,1]])
print(ar2)
print()
#행방향 솔트
sort=np.sort(ar2,axis=0)
print(sort)
print()
#열방향
sort=np.sort(ar2,axis=1)
print(sort)

[[ 8 12]
 [ 7  1]]

[[ 7  1]
 [ 8 12]]

[[ 8 12]
 [ 1  7]]


In [102]:
#정렬행렬의 인덱스 반환
ar=np.array([3,1,9,5])
print(ar)
print(np.argsort(ar))

[3 1 9 5]
[1 0 3 2]


In [105]:
#행렬 내적
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])

np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [110]:
a=np.array([[1,2],[3,4]])
a.transpose()
a.T

array([[1, 3],
       [2, 4]])